# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
---
type: "displaymanager"
name: "Display Manager"

# A list of display managers to try to set up.
# The first one that is installed will be used.
#
# available: "gdm", "lightdm", "lxdm", "sddm"
# default: []
#
# displayManagers: [ "gdm", "lightdm", "lxdm", "sddm" ]
displayManagers: [ "sddm" ]
