# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
---
type: "packagechooser"
name: "Select Packages"

# A list of packages to select from.
# Each package has a name, a description, and a boolean indicating
# whether it is selected by default.
packages:
    - name: "yay"
      description: "An AUR helper"
      selected: true
    - name: "google-chrome"
      description: "The Google Chrome web browser"
      selected: false
