efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    1000MiB
    minimumSize:        32MiB
    label:              "EFI"

drawNestedPartitions:   false
enableLuksAutomatedPartitioning:    false

alwaysShowPartitionLabels: true
allowManualPartitioning: false

initialPartitioningChoice: none

initialSwapChoice: none

defaultFileSystemType:  "ext4"

availableFileSystemTypes:  ["ext4","btrfs","f2fs","jfs","reiser","xfs"]

partitionLayout:
    - name: "boot"
      filesystem: "ext2"
      mountPoint: "/boot"
      size: 2G
      minSize: 2G
    - name: "root"
      filesystem: "ext4"
      mountPoint: "/"
      size: 100%
      minSize: 10G